# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12 # https://pyreadiness.org/3.10
  - pip=23.2.1 # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0 # https://pypi.org/project/robocorp-truststore/
  - pip:
      - rpaframework==24.0.0 # https://rpaframework.org/releasenotes.html
      - robocorp==0.8.1 # https://pypi.org/project/robocorp
      - robocorp-browser==2.0.1 # https://pypi.org/project/robocorp-browser
      - robocorp-excel==0.4.0 # https://pypi.org/project/robocorp-excel
      - robocorp-http==0.2.0 # https://pypi.org/project/robocorp-http
      - chromedriver-py==88.0.4324.96
      - pillow>=8.0.0
